/**
 * @NApiVersion 2.1
 * @NScriptType Suitelet
 *
 * BCCombineAttachedRecordsSuitelet
 *
 * 1. Reads the current record's own lines and collects the source transaction
 *    IDs from custcol_bc_tm_source_transaction on each line.
 * 2. For each of those transactions, pulls ALL of its natively attached files
 *    (Communication > Files tab attachments - NOT the custbody_bc_attached_record
 *    field) that are PDFs.
 * 3. Appends the PDF generated by the ESG invoice-print Suitelet
 *    (customscript_esg_print_inv_pdf / customdeploy1) as the LAST page of the
 *    merge, after the compiled attached-record PDFs. The Suitelet is called
 *    server-side (https.requestSuitelet) with recID (this invoice's internal
 *    id), projID (the internal id in this record's header cseg_bc_project
 *    field), plus output=fileid & folderID, which makes it SAVE its rendered
 *    PDF into the File Cabinet and respond with the saved file's internal id.
 *    That file's (online) File Cabinet URL is what goes into the <pdfset> -
 *    the BFO render engine can only pull File Cabinet content, NOT live
 *    Suitelet URLs ("Error Parsing XML: //...extforms..."), which is why the
 *    PDF must be saved as a real file before the merge. This replaces the old
 *    inline "Time Detail" XML report that used to be built by hand here.
 * 4. Merges all of the attached PDFs plus the print-Suitelet page (last) into
 *    a single combined PDF.
 * 5. Attaches that combined PDF onto the CURRENT record natively
 *    (Communication > Files tab, via record.attach()) rather than writing it
 *    into the custbody_bc_attached_record field.
 *
 * NOTE: the current record is loaded as 'invoice'. Change RECORD_TYPE below if
 * this needs to run against a different transaction type.
 *
 * NOTE: requires the companion patch in customscript_esg_print_inv_pdf that
 * handles the output=fileid parameter (save rendered PDF to folderID, respond
 * with the file id) - see the patch block supplied alongside this script.
 */
define(['N/record', 'N/render', 'N/search', 'N/file', 'N/xml', 'N/https'],
    (record, render, search, file, xml, https) => {

        var RECORD_TYPE = 'invoice';
        var LINE_SUBLIST = 'item';
        var LINE_SOURCE_FIELD = 'custcol_bc_tm_source_transaction';

        // The Suitelet that renders the invoice/project print PDF appended as
        // the final page of the merge (replaces the old inline Time Detail
        // report), and the parameter names it expects on its URL.
        var PRINT_PDF_SCRIPT_ID = 'customscript_esg_print_inv_pdf';
        var PRINT_PDF_DEPLOYMENT_ID = 'customdeploy1';
        var PRINT_PDF_PARAM_REC = 'recID';   // invoice internal id
        var PRINT_PDF_PARAM_PROJ = 'projID'; // cseg_bc_project internal id

        const onRequest = (context) => {
            try {
                var recId = parseInt(context.request.parameters.recId);
                if (!recId) {
                    log.error('No Record ID passed to SuiteLet');
                    return false;
                }

                var rec = record.load({ type: RECORD_TYPE, id: recId, isDynamic: true });
                var getTranId = rec.getValue('tranid');

                var folderId = getFolderId(recId);
                var attachedRecordUrls = [];



                // 1. The ESG invoice-print Suitelet's PDF, appended as the LAST
                //    page of the merge below - the compiled attached-record PDFs
                //    print first, the Suitelet result last. The Suitelet is asked
                //    (output=fileid) to save its rendered PDF into this record's
                //    folder and hand back the file id; the saved file's File
                //    Cabinet URL is what the <pdfset> can actually fetch.
                var printPdfUrl = getPrintSuiteletPageUrl(rec, recId, folderId);
                if (printPdfUrl) {
                    attachedRecordUrls.push(printPdfUrl);
                }


                // 2. Source transaction IDs pulled straight off this record's own
                //    lines (custcol_bc_tm_source_transaction), instead of a search.
                var linkedTranIds = getLinkedTransactionIds(rec);

                // 3. Every native file attachment (PDF) on each of those transactions.
                getAttachedPdfUrls(linkedTranIds, attachedRecordUrls);

                // 4. Merge them all into a single combined PDF.
                var combinedFileId = null;
                if (attachedRecordUrls.length !== 0) {
                    var tpl = ['<?xml version="1.0"?>', '<pdfset>'];
                    attachedRecordUrls.forEach(function (url) {
                        tpl.push("<pdf src='" + xml.escape({ xmlText: url }) + "'/>");
                    });
                    tpl.push('</pdfset>');

                    var combinedPdf = render.xmlToPdf({ xmlString: tpl.join('\n') });
                    combinedPdf.name = (getTranId || recId) + ' - Attached Records Combined.pdf';
                    combinedPdf.folder = folderId;
                    combinedPdf.isOnline = true;
                    combinedFileId = combinedPdf.save();
                    log.debug('Combined attached-record PDF saved', combinedFileId);
                } else {
                    log.audit('No attached PDFs found to combine', { recId: recId });
                }

                // 5. Attach the merged PDF to the CURRENT record natively - the same
                //    Communication > Files tab attachment mechanism read by
                //    getAttachedPdfUrls() above - instead of writing its file id
                //    into the custbody_bc_attached_record field.
                //
                // record.attach() only inserts a file-to-transaction attachment
                // row; it never loads or saves the invoice record itself, so there
                // is no field-level validation of any kind to trip. This sidesteps
                // the FIELDS_1_CANNOT_BE_CHANGED_AFTER_INVOICE_IS_GROUPED error a
                // record.submitFields()/save() call could previously hit on
                // invoices that have gone through group billing/consolidation.
                if (combinedFileId) {
                    // record.Type has no FILE member - record.Type.FILE silently
                    // evaluates to undefined, which is what triggered
                    // "Missing a required argument: record.type". Files are
                    // attached using the plain string 'file' instead.
                    record.attach({
                        record: { type: 'file', id: combinedFileId },
                        to: { type: RECORD_TYPE, id: recId }
                    });
                    log.debug('Combined PDF attached to record', { recId: recId, fileId: combinedFileId });

                    var combinedFileObj = file.load({ id: combinedFileId });
                    return context.response.writeFile({ file: combinedFileObj, isInline: true });
                }

                return context.response.write({ output: 'No attached PDFs found to combine for record ' + recId });

            } catch (err) {
                log.error('onRequest ERROR', err);
            }
        };

        /**
         * Reads custcol_bc_tm_source_transaction off every line of the current
         * record (loaded dynamic) and returns the distinct, non-empty
         * transaction IDs referenced.
         */
        function getLinkedTransactionIds(rec) {
            var idSet = {};
            var ids = [];

            var lineCount = rec.getLineCount({ sublistId: LINE_SUBLIST });
            for (var i = 0; i < lineCount; i++) {
                var sourceTranId = rec.getSublistValue({
                    sublistId: LINE_SUBLIST,
                    fieldId: LINE_SOURCE_FIELD,
                    line: i
                });

                if (sourceTranId && !(sourceTranId in idSet)) {
                    idSet[sourceTranId] = true;
                    ids.push(sourceTranId);
                }
            }

            log.debug('getLinkedTransactionIds', ids);
            return ids;
        }

        /**
         * For a list of transaction internal ids, finds EVERY natively attached
         * PDF file on each transaction (via the 'file' join - the record's own
         * Communication > Files attachments, not any custom field), flips each
         * one online so its URL is retrievable without login, and returns the
         * resulting URLs. Files are grouped by transaction (in tranIds order,
         * de-duplicated) and, within a transaction, ordered by file internal id
         * ascending for stable/deterministic output.
         */
        function getAttachedPdfUrls(tranIds, urls) {
            //var urls = [];
            if (!tranIds || tranIds.length === 0) return urls;

            // Collect every PDF file attached to each transaction. No "keep going
            // until we've seen each transaction once" early-stop here - we want
            // every matching row.
            var fileIdsByTran = {};
            search.create({
                type: 'transaction',
                filters: [
                    ['internalid', 'anyof', tranIds],
                    'AND', ['mainline', 'is', 'T'],
                    'AND', ['file.filetype', 'anyof', 'PDF']
                ],
                columns: [
                    search.createColumn({ name: 'internalid' }),
                    search.createColumn({ name: 'internalid', join: 'file', sort: search.Sort.ASC })
                ]
            }).run().each(function (result) {
                var tranId = result.getValue({ name: 'internalid' });
                var fileId = result.getValue({ name: 'internalid', join: 'file' });
                if (fileId) {
                    if (!fileIdsByTran[tranId]) fileIdsByTran[tranId] = [];
                    if (fileIdsByTran[tranId].indexOf(fileId) === -1) {
                        fileIdsByTran[tranId].push(fileId);
                    }
                }
                return true; // keep going - collect every row, not just the first per transaction
            });

            var fileIds = [];
            tranIds.forEach(function (tranId) {
                (fileIdsByTran[tranId] || []).forEach(function (fileId) {
                    if (fileIds.indexOf(fileId) === -1) fileIds.push(fileId);
                });
            });

            if (fileIds.length === 0) {
                log.audit('getAttachedPdfUrls', 'No PDF attachments found for the given transactions');
                return urls;
            }

            // Flip files online so their URLs are retrievable without auth.
            search.create({
                type: 'file',
                filters: [['internalid', 'anyof', fileIds], 'AND', ['availablewithoutlogin', 'is', 'F']],
                columns: [search.createColumn({ name: 'url' })]
            }).run().each(function (result) {
                var f = file.load({ id: result.id });
                f.isOnline = true;
                f.save();
                return true;
            });

            search.create({
                type: 'file',
                filters: [['internalid', 'anyof', fileIds], 'AND', ['availablewithoutlogin', 'is', 'T']],
                columns: [search.createColumn({ name: 'url' })]
            }).run().each(function (result) {
                urls.push(result.getValue('url'));
                return true;
            });

            log.debug('getAttachedPdfUrls', urls);
            return urls;
        }

        /**
         * Calls the ESG invoice-print Suitelet
         * (customscript_esg_print_inv_pdf / customdeploy1) server-side and
         * returns the File Cabinet URL of the PDF it saved, for use as the
         * last <pdf src> page of the master <pdfset> merge.
         *
         * Parameters sent:
         *   - recID    = this invoice's internal id
         *   - projID   = the internal id in this record's header
         *                cseg_bc_project field (the print Suitelet
         *                record.load()s customrecord_cseg_bc_project with it,
         *                so the VALUE is passed, not the display text)
         *   - output   = 'fileid' - tells the (patched) print Suitelet to SAVE
         *                its rendered PDF to the File Cabinet and respond with
         *                the saved file's internal id, instead of streaming
         *                the PDF inline
         *   - folderID = the record's own folder (same one the combined PDF
         *                is saved into), so the print page lands next to it
         *
         * Why not just put the Suitelet's URL into the <pdfset> directly: the
         * BFO render engine behind render.xmlToPdf can only retrieve File
         * Cabinet content - a live scriptlet.nl URL fails with "Error Parsing
         * XML: //...extforms.netsuite.com/...". And why not save the response
         * body from this side: N/https returns bodies as strings, which
         * corrupts binary PDF content. Having the print Suitelet save its own
         * render (a file.File from renderAsPdf) avoids both problems.
         *
         * Returns null (page skipped, merge continues without it) when the
         * record has no cseg_bc_project value or the call fails.
         */
        function getPrintSuiteletPageUrl(rec, recId, folderId) {
            var projId = rec.getValue({ fieldId: 'cseg_bc_project' });
            if (!projId) {
                log.audit('getPrintSuiteletPageUrl', 'No cseg_bc_project value on this record - skipping print Suitelet page');
                return null;
            }

            try {
                var urlParams = {};
                urlParams[PRINT_PDF_PARAM_REC] = recId;
                urlParams[PRINT_PDF_PARAM_PROJ] = projId;
                urlParams.output = 'fileid';
                urlParams.folderID = folderId;

                // NOTE: no `external` option here - NetSuite removed it from
                // https.requestSuitelet() (REQUEST_SUITELET_NO_LONGER_SUPPORTS_
                // EXTERNAL_PARAMETER). The API now resolves and authenticates
                // the Suitelet call itself.
                var response = https.requestSuitelet({
                    scriptId: PRINT_PDF_SCRIPT_ID,
                    deploymentId: PRINT_PDF_DEPLOYMENT_ID,
                    method: https.Method.GET,
                    urlParams: urlParams
                });

                var printFileId = parseInt((response.body || '').trim());
                if (!printFileId) {
                    log.error('getPrintSuiteletPageUrl', 'Print Suitelet did not return a file id. HTTP ' + response.code +
                        ', body: ' + String(response.body || '').substring(0, 500));
                    return null;
                }

                // The print Suitelet saves the file isOnline already; belt and
                // braces in case that ever changes, since the merge fetch
                // requires an online URL.
                var printFile = file.load({ id: printFileId });
                if (!printFile.isOnline) {
                    printFile.isOnline = true;
                    printFileId = printFile.save();
                    printFile = file.load({ id: printFileId });
                }

                log.debug('getPrintSuiteletPageUrl', 'file ' + printFileId + ' url=' + printFile.url);
                return printFile.url;

            } catch (err) {
                log.error('getPrintSuiteletPageUrl ERROR', err);
                return null;
            }
        }

        /**
         * Resolves (or creates) the SuiteScripts folder named after the record id,
         * under parent folder 7707 — same as getFolderId() in the original script.
         */
        function getFolderId(getRecId) {
            try {
                var folderSearchObj = search.create({
                    type: 'folder',
                    filters: [['name', 'is', getRecId], 'AND', ['parent', 'anyof', '7707']],
                    columns: [search.createColumn({ name: 'name' })]
                });
                var folderId = '';
                if (folderSearchObj.runPaged().count === 0) {
                    var objRecord = record.create({ type: record.Type.FOLDER, isDynamic: true });
                    objRecord.setValue({ fieldId: 'name', value: getRecId });
                    objRecord.setValue({ fieldId: 'parent', value: 7707 });
                    folderId = objRecord.save({ enableSourcing: true, ignoreMandatoryFields: true });
                } else {
                    folderSearchObj.run().each(function (result) { folderId = result.id; });
                }
                return folderId;
            } catch (err) {
                log.error('getFolderId ERROR', err);
            }
        }

        var exports = {};
        exports.onRequest = onRequest;
        return exports;
    });